name: Build Jekyll Pages

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: bom-check
      uses: arma-actions/bom-check@v1.0
      with:
        path: _conferences

    - name: Validate conference data file names
      run: ls -1 _conferences/ | grep -v '\.md$' && echo "Found above file names not ending in '.md'. Please correct." && exit 1 || true

    - name: Prepare for conference data file validation
      run: |
        mkdir _tmp

        # Copy conference data files and rename to .yml because pykwalify is picky
        for file in _conferences/*.md; do
          name=${file#"_conferences/"}
          name=${name%".md"}
          cp -- "$file" "_tmp/${name}.yml"
        done

        # Strip everything but the YAML front matter block
        sed -ni '/---/{:a;n;/---/b;p;ba}' _tmp/*.yml

    - name: Validate conference data files
      uses: cketti/action-pykwalify@v0.3-temp-fix
      with:
        files: _tmp/*.yml
        schema: conference_schema.yml

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Build with jekyll
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec jekyll build
